spring:
  shardingsphere:
    datasource:
      names: primary_ds,replica_ds_0,replica_ds_1
      primary_ds:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/chongba_schedule?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: root
      replica_ds_0:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/chongba_schedule1?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: 123456
      replica_ds_1:
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/chongba_schedule2?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8
        password: root
        type: com.zaxxer.hikari.HikariDataSource
        username: 123456
    rules:
      replica-query:
        data-sources:
          pr_ds:
            load-balancer-name: round-robin
            primary-data-source-name: primary_ds
            replica-data-source-names: replica_ds_0,replica_ds_1
        load-balancers:
          round-robin:
            props:
              workid: 123
            type: ROUND_ROBIN
    enabled: true