#spring:
#  application:
#    name: schedule-service #服务名
#  datasource:
#    url: jdbc:mysql://192.168.200.129:3306/chongba_schedule?serverTimezone=Asia/Shanghai
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 123456

spring:
  datasource:
    master: # 写账户
      jdbc-url: jdbc:mysql://localhost:3306/chongba_schedule?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    slave1: # 只读账户
      jdbc-url: jdbc:mysql://192.168.200.129:3306/chongba_schedule?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
    slave2: # 只读账户
      jdbc-url: jdbc:mysql://192.168.200.129:3306/chongba_schedule?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456